service: ieso-zonal-demand
useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:service}-${sls:stage}-stack
  iam:
    role:
      name: ${self:service}-${sls:stage}-lambda-role
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:AbortMultipartUpload
            - s3:GetBucketLocation
            - s3:ListBucket
            - s3:ListBucketMultipartUploads
          Resource:
            - arn:aws:s3:::com.dsa.ieso-project/*
            - arn:aws:s3:::${env:TARGET_BUCKET, 'com.dsa.ieso-project'}/*
            - arn:aws:s3:::com.dsa.ieso-project
            - arn:aws:s3:::${env:TARGET_BUCKET, 'com.dsa.ieso-project'}
  environment:
    TARGET_BUCKET: ${env:TARGET_BUCKET}
    TARGET_PREFIX: ${env:TARGET_PREFIX}
    TIMEOUT_SECONDS: ${env:TIMEOUT_SECONDS}
    S3_SERVER_SIDE_ENCRYPTION: ${env:S3_SERVER_SIDE_ENCRYPTION}
    LOG_LEVEL: ${env:LOG_LEVEL}
    NORMALIZE_LONG_FORMAT: ${env:NORMALIZE_LONG_FORMAT}
    WRITE_LOCAL_COPY: ${env:WRITE_LOCAL_COPY}
    LATEST_ONLY: ${env:LATEST_ONLY, 'false'}
    YESTERDAY_ONLY: ${env:YESTERDAY_ONLY, 'true'}

  ecr:
    images:
      ieso-zonal-image:
        path: ./

functions:
  ieso-zonal-demand-to-s3:
    name: ${self:service}-${sls:stage}-to-s3
    image:
      name: ieso-zonal-image
    timeout: ${env:TIMEOUT_SECONDS}
    events:
      - schedule:
          name: ${self:service}-${sls:stage}-daily-trigger
          rate: cron(15 3 * * ? *)
          description: "Trigger Lambda daily at 3:15 AM UTC to pull data for the day before"

plugins:
# - serverless-python-requirements # No longer needed for Docker deployment
